### PR TITLE
- RR: Tie player input to framerate

### PR DESCRIPTION
**Pull request by mjr4077au**
This set of commits is to bring the input code of RR up to the same level as the pull request for Duke 3D.

More effort was needed here as the RR code is a mess and has not been adequately kept up to date with Duke3D code.

Only Duke 3D and Redneck Rampage have been tested. Rides Again and Deer Hunting do not work against the current versions of Raze irrespective of these changes and therefore are untested.

### CODE REVIEW

**Comment by coelckers** [comment]
Why didn't you report that RRRA and Deer Huntin' were broken as a bug?

**Comment by mjr4077au** [comment]
I'm sorry, I thought there was no expectation for them to be working (at least or Dee Huntin'). I'll report the issues shortly.

Any thoughts or feedback regarding this and the other pull request? Do you need more time to review/test them, etc?

**Comment by coelckers** [comment]
I already fixed RRRA and Deer Huntin's startup. That was caused by some incomplete and abandoned refactoring which I undid again. I just didn't know they were broken.

Regarding the features, be advised that I am currently not working on Raze except for fixing serious bugs I am made aware of. Too much stress because of coronavirus interfering with normal work patterns. So this probably won't change for the coming weeks. :(

I'm afraid that this also means I cannot do the needed review work for these PRs for the time being. Just make sure they work and don't get closedd and once I can invest more time here again they should be merged.

**Comment by mjr4077au** [comment]
The games start, but I get no menu, just a tiled background. I'll double-check it's nothing to do with bad files on my end.

Completely understood about the PRs and whatnot, just look after No. 1 for now :). I'll make sure they stay open. They work against the current master and played through a number of levels with no issues.

Stay safe!

**Comment by coelckers** [comment]
I already fixed it, Pulling again should give you a working version.

**Comment by mjr4077au** [comment]
Ah no worries, I misunderstood sorry. I guess more effort towards that consolidation can occur in the future :)

**Comment by mjr4077au** [comment]
Now that RRRA is working, I was able to test the commits out. Some work was needed so I've pushed more changes. I was able to simplify the code in these functions significantly.

For Deer Huntin', the code in master doesn't work. The viewport is constantly held ~45 degrees from centre and you can't move it. The input changes in this pull request repair this by happenstance.

**Comment by coelckers** [comment]
Merged manually

**Pull request closed without merging**
