### PR TITLE
Unified saved games and demos paths handing for all platforms

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
The current game subdirectory is now created on all platforms
`cl_savedir` CVAR and `-savedir` command line switch are supported on all platforms

### CODE REVIEW

**Comment by coelckers** [comment]
I'm not sure if it is a good idea to add the LumpFilter if an explicit path is set on the command line - adding another unwanted subfolder in that case defeats the purpose of explicitly specifying a location.

**Comment by alexey-lysiuk** [comment]
Indeed, it's arguable for `-savedir` switch. I'll change it back then. The rest is OK, right?

**Comment by coelckers** [comment]
Yes, that's the only issue I have with it.

**Comment by alexey-lysiuk** [comment]
On the second thought, `cl_savedir` CVAR has `LumpFilter` added to the path, although it has an independent value per each game. Should it be made `CVAR_GLOBALCONFIG` then?

**Comment by coelckers** [comment]
I'd say yes. Make it global. Just -savedir should be absolute so that it can be used by launch tools to set the engine up to their own needs.

**Comment by alexey-lysiuk** [comment]
Force pushed the requested changes (the first commit).

**Pull request merged**
