### PR TITLE
Eliminate dependency on linking order for autosegs

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
Draft solution for linking order issue from #164, implemented for Windows only so far.

### CODE REVIEW

**Comment by coelckers** [comment]
Do I read this correctly that instead of merging everything into the data segment, this keeps these sections as separate segments?

**Comment by alexey-lysiuk** [comment]
Yes, these sections need to be separated inside executable.

**Comment by mjr4077au** [comment]
> Yes, these sections need to be separated inside executable.

Could that affect performance (i.e. will LTO still apply)?

**Comment by coelckers** [comment]
No, this just reorganizes the static data to be more reliably ordered.

**Comment by alexey-lysiuk** [comment]
Implemented the change for all platforms.

**Comment by mjr4077au** [comment]
Graf will have to review this one, I'm far too green to cast an opinion on something like this. Thanks for addressing this issue though 😁.

**Comment by coelckers** [comment]
All I can say is "it works".
But I have to admit that the code here is a textbook example of where modern C++ went wrong. I seriously have to ask why generic programming always ends up in code that looks totally fucked up. Why can't these things be done with a nicer syntax? In this regard C++ is a hideous hack language.

**Comment by alexey-lysiuk** [comment]
Yeah, it took some time to make it work. Please note that I tried to keep it readable as much as possible.
Also, these complications with type traits are needed for GZDoom where early exit from for-each loop is used.

**Comment by coelckers** [comment]
TBH, I wouldn't have tried this approach but simply have used 2 different function names for the 2 cases.
So far every time I tried using this generic stuff it failed.

**Pull request merged**
