### PR TITLE
Blood: Fix issues with weapon not switching properly if cycling the weapons too quickly.

### PR DESCRIPTION
**Pull request by mjr4077au**
- This means that while weapons can't be changed mid-animation, they switch consistently. I feel they animate quick enough, anyway.

### CODE REVIEW

**Comment by sinisterseed** [comment]
Honestly I'm not too sure about the lost of the ability to switch weapons mid-animation, if these changes also have an impact on it. I remember back when Fresh Supply was still being updated that many people complained about quirks and tricks like this not working in it, and they got eventually patched in again.

I think people who employ these tricks in their gameplay for various reasons will be quite displeased by this change. Could the goal of this PR be achieved without the lost of this functionality?

**Comment by mjr4077au** [comment]
> Honestly I'm not too sure about the lost of the ability to switch weapons mid-animation, if these changes also have an impact on it. I remember back when Fresh Supply was still being updated that many people complained about quirks and tricks like this not working in it, and they got eventually patched in again.
> 
> I think people who employ these tricks in their gameplay for various reasons will be quite displeased by this change. Could the goal of this PR be achieved without the lost of this functionality?

It could be put behind a boolean or something to give users the choice. Maybe I'm alone in this but when I try to scroll through the weapons without this fix, it gives the experience of basically just bringing the pitchfork up and down.

The comment is all fair and well, but download the [artifact](https://github.com/coelckers/Raze/suites/731292152/artifacts/7336287) left over from the CI integration testing and see what you think :).

**Comment by mjr4077au** [comment]
Should I perhaps just close this one down? Seems like it's a bit controversial.

**Comment by sinisterseed** [comment]
> Should I perhaps just close this one down? Seems like it's a bit controversial.

Well, if Graf decides to merge it I am not **_necessarily_** against it, it's just the fact that it kills the weapon switching trick if done this way, and I know for a fact a change like this will cause backlash later on, especially since there is a precedent for this now - as I said, stuff like this is exactly why Fresh Supply was harshly criticized by many Blood fans, in addition to the generally unfaithful gameplay.

I'd just like have these quirks preserved, but at the same time this also does fix a bug as well, so I dunno what's worse.

**Comment by mjr4077au** [comment]
What exactly is the "weapon switching trick"? I spin the wheel and all that happens is the pitchfork goes up and down, it doesn't cycle the weapons unless I ensure I do one mouse roll at a time.

I definitely don't want any backlash and am concerned for accuracy, you saw how I persisted with the lighting stuff. Realistically, there wasn't even scroll wheels in 1997 so I'm not sure how much backlash there could be.

**Comment by sinisterseed** [comment]
> What exactly is the "weapon switching trick"?

Changing weapons mid-animation, I've seen Youtubers doing this so it doesn't seem to be a rare occurrence when people employ it. See 0:30 here for what I mean, first is FS then GDX - https://www.youtube.com/watch?v=jGUAUdCkPTU

**Comment by mjr4077au** [comment]
I'll have to test BloodGDX but from what I could tell, no "mid animation" switching was occurring, the switching occured as fast as the weapon goes up and down.

Just wondering whether you've tested this change at all or are the comments somewhat speculatory? Direct link to a CI artifact is [here](https://github.com/coelckers/Raze/suites/731292152/artifacts/7336287) if you want to test.

**Comment by sinisterseed** [comment]
> I'll have to test BloodGDX but from what I could tell, no "mid animation" switching was occurring, the switching occured as fast as the weapon goes up and down.
> 
> Just wondering whether you've tested this change at all or are the comments somewhat speculatory? Direct link to a CI artifact is [here](https://github.com/coelckers/Raze/suites/731292152/artifacts/7336287) if you want to test.

Just did, and apparently I might've misunderstood the issue honestly. Damn.

Tried to do it with your CI artifact and it seems fine regardless, but I am not 100% convinced this time around, so I'm gonna need a second opinion here. If it still works like in GDX it should be mighty fine. Ugh, I've been a roadblock to progress the whole time if all this was is a misunderstanding.

**Comment by mjr4077au** [comment]
It's honestly not a problem, I appreciate the careful consideration with such things ☺️

**Comment by sinisterseed** [comment]
> It's honestly not a problem, I appreciate the careful consideration with such things ☺️. I can't request reviews being an outsider but I'm sure Graf will see all this at some point and cast his opinion.

But I would also like to hear your opinion about how GDX does thiis, just to be sure everything's fine ;) .

**Comment by mjr4077au** [comment]
> > It's honestly not a problem, I appreciate the careful consideration with such things ☺️. I can't request reviews being an outsider but I'm sure Graf will see all this at some point and cast his opinion.
> 
> But I would also like to hear your opinion about how GDX does thiis, just to be sure everything's fine ;) .

I'll test it tonight but still hope this can get merged irrespective. I feel it's necessary since the input code is processed at sub-tick intervals now which is what's leading to this fault in the first place. The fix just makes it work like it did before the uninterpolated aiming code was merged.

**Comment by sinisterseed** [comment]
> > > It's honestly not a problem, I appreciate the careful consideration with such things ☺️. I can't request reviews being an outsider but I'm sure Graf will see all this at some point and cast his opinion.
> > 
> > 
> > But I would also like to hear your opinion about how GDX does thiis, just to be sure everything's fine ;) .
> 
> I'll test it tonight but still hope this can get merged irrespective. I feel it's necessary since the input code is processed at sub-tick intervals now which is what's leading to this fault in the first place. The fix just makes it work like it did before the uninterpolated aiming code was merged.

Alright then. In this case, I think it's about time to merge this, after wasting so much time over a concern that was ultimately unfounded.

**Pull request merged**
