### PR TITLE
[Blood] Add modern map kViewEffectSpotProgress support

### PR DESCRIPTION
**Pull request by carnivoroussociety**
This PR adds the currently missing effect kViewEffectSpotProgress. This is used in the [recent mod Eviction](https://www.moddb.com/mods/eviction-addon-for-blood).

example

### CODE REVIEW

**Comment by mjr4077au** [comment]
I'll leave this one for Graf to approve as I'm unsure whether it was left out on purpose or whether it was an accident. It's not from NoOne's most recent additions, but his ones from December 2020.

**Comment by carnivoroussociety** [comment]
Sure, I've checked over nnexts.cpp and this appears to be the only missing effect.

**Comment by mjr4077au** [comment]
I just added it, I'm sure it was an accident so now reason to leave it sit here. Thanks again! 😁

**Comment by carnivoroussociety** [comment]
Welcome, thanks for the quick merge!

**Comment by mjr4077au** [comment]
Anything before 9 pm my time gets picked up by the daily devbuild bot. Only 75 minutes until 9 pm 😉

**Comment by coelckers** [comment]
No idea where this got missed. I thought I had gotten all of the additions.

**Comment by mjr4077au** [comment]
That's the problem with these monster commits, so easy for things to get missed or sneak in accidently.

**Pull request merged**
