### PR TITLE
- fix LCtrl bindings in wadsrc keybind preset files.

### PR DESCRIPTION
**Pull request by mjr4077au**
* Renamed LCtrl to Ctrl. Without these changes, the keybinds for LCtrl in the changed keybind preset files weren't binding.

### CODE REVIEW

**Comment by sinisterseed** [comment]
> * Distinction between LCtrl and RCtrl disappeared with the backend sync. **Without these changes, crouch isn't binding anymore.**

It doesn't? The distinction has indeed disappeared, but both Control keys still work for me when I bind them to Crouch.

**Comment by mjr4077au** [comment]
*binding with the presets 😉

**Comment by coelckers** [comment]
The distinction has not disappeared, but is not subject to the k_mergekeys CVAR like in GZDoom. SO please edit the configs accordingly. The actual difference in the engine is merely the change of key names for the left variants.

**Comment by mjr4077au** [comment]
Just to make sure I've got it right, revert the changes to RCtrl and the rest is fine?

**Comment by coelckers** [comment]
Yes

**Comment by mjr4077au** [comment]
That's the first and last time I'll ever do a commit from a mobile phone, that took 7 times longer than it should...

Force pushed to clean things up, should be all good now I hope. Thanks for enlightening me on that CVAR also.

**Pull request merged**
