### PR TITLE
[Blood] Improved GetClosestSpriteSectors() detection

### PR DESCRIPTION
**Pull request by carnivoroussociety**
This PR fixes two design flaw with function `GetClosestSpriteSectors()`. The issues are as follows:
- Only checks next sector once (assumes current sector only links to next sector once - this causes the issue in E1M2)
- Assumes wall spans are within the range check (breaks with wide spans - see E6M2/big board videos)

The PR will fix both these issues with the following changes:
- Only flag next sector as checked if rest of sector's walls no longer reference to next sector
- Test midpoints if wall length is greater than range*1.5, and iterate towards target until point is found (capped off at 4 times)

By fixing this it'll now improve explosion damage calculations instead of randomly doing no damage simply by being in the middle of wide spans, or not close to the first wall in a multi connected sector. By default the `GetClosestSpriteSectors()` fix will be disabled unless `newSectCheckMethod` is set on. I've added `VanillaMode()` checks to all calls.

Example videos:
- E1M2: [before](https://user-images.githubusercontent.com/38839485/129851582-28f6afbb-272e-4c91-8c42-42e26c41235b.mp4)/[after](https://user-images.githubusercontent.com/38839485/129851249-5d7247f6-0f07-4d16-abc9-e483ed84014a.mp4)
- E6M1: [before](https://user-images.githubusercontent.com/38839485/129851608-238ec971-a264-4a55-a564-0bbb089fc3c1.mp4)/[after](https://user-images.githubusercontent.com/38839485/129851332-f6be8b08-1564-4cc1-9267-e2778c691f48.mp4)
- DWE3M2: [before](https://user-images.githubusercontent.com/38839485/129852137-c4a6a056-01e0-4330-a01e-56c19bcf3b00.mp4)/[after](https://user-images.githubusercontent.com/38839485/129852101-98776144-6e4c-4c61-8025-b043af0a5a35.mp4)
- Wide span test map: [before](https://user-images.githubusercontent.com/38839485/129851518-03dda628-2f53-421c-a1d7-2ebec30afcbd.mp4)/[after](https://user-images.githubusercontent.com/38839485/129851655-56c8778c-59f5-4faa-bf2d-e94d2fbff7e6.mp4)

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
I am very much in favor of these fixes, as I noticed the problems with ineffective explosions myself, but considering how their impact on game behavior is I think this needs a compatibility switch CVAR in addition to the VanillaMode check - at least for everything concerning explosions, so that we can point to that in case someone complains about changing gameplay behavior like this.

**Comment by mjr4077au** [comment]
Off-topic to that, I just wanted to express my genuine appreciation for the renamed disassembly function and variable names 😁

**Comment by carnivoroussociety** [comment]
Thanks for reviewing, yes I am in entire agreement that this should be an optional gameplay feature. I'll look into adding a new explosions behavior option within game settings then - thank you.

**Comment by sinisterseed** [comment]
This just ruined the game for me lol.

So THIS is why Blood's explosions were so horribly inconsistent, it was an issue with sectors? I'm so glad this infamous bug has been fixed now, safety checks or not.

**Comment by coelckers** [comment]
> 
> 
> This just ruined the game for me lol.
> 
> So THIS is why Blood's explosions were so horribly inconsistent, it was an issue with sectors? I'm so glad this infamous bug has been fixed now, safety checks or not.

Yeah, me, too. I just noticed yesterday when some dynamite refused to kill a bunch of cultists at point blank range.
Makes sense, though that it is caused by broken sector traversal.
But be it as it may, this is precisely the stuff the purists will never accept seeing fixed so the switch is unavoidable.

**Review by coelckers — APPROVED** [review]
Looks ok in general.
Next time, please post the texts in a comment instead of modifying the machine generated language.csv file.

They need to be inserted into the language spreadsheet on Google Docs and having them as plain text makes it much easier to copy them over.

**Comment by carnivoroussociety** [comment]
Thank you, I'll be sure to do that next time - wasn't aware how language files are generated.

**Pull request merged**
