### PR TITLE
[issues forms] new issue Forms design using YAML schema markdown

### PR DESCRIPTION
**Pull request by arrowgent**
example results:
https://github.com/arrowgent/Raze/issues

test yourself by starting an issue

files changed:
https://github.com/arrowgent/Raze/tree/master/.github/ISSUE_TEMPLATE

issue conversation:
https://github.com/coelckers/Raze/issues/531

recent Beta release:
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

converting from template markdown to YAML:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

im new to YAML
i think Version can be reworked to automatically pull from Releases, if possible somehow to automatically add new lines here from your workflows?
so you dont have to always update the version in bug_report.yaml

### CODE REVIEW

**Comment by coelckers** [comment]
Two things:

1. In the list of games, NAM and WW2GI are missing. While minor titles we need them for completeness.
2. Do we really need that legalese checkbox at the end? I often find that these things serve more as a deterrent for posting than anything else.

It also feels like a lot to process for the potential reporter. I guess we can only wait and see if this makes things work better or not.

**Comment by arrowgent** [comment]
just a generic suggestion for contribution guidelines and conduct,  i notice you dont have one posted in the folder.

**It is also capable of playing Nam and WW2 GI.**

great i missed those, i can add them

**Comment by coelckers** [comment]
I think all we can do here is to apply the change and see how people react.

**Comment by arrowgent** [comment]
great.

im working on another one right now.


let me know if you want me to create similar on gzdoom?

**Comment by coelckers** [comment]
Why not? We still use the forum mainly over there for engagement reasons but it's surely worth a try.

**Pull request merged**
