### PR TITLE
Input continuation

### PR DESCRIPTION
**Pull request by mjr4077au**
I feel this should be ready to present now and receive further testing.

The changes here make full use of your binangle and fixedhoriz class in lieu of discrete game-side variables. Being able to have a single object and return BAM, Q16.16 or Build values with a simple method call is great and really eased this conversion process.

As per discussions, wrapped a few binangle and fixedhoriz objects into a simple struct with some methods to process the data within such as setting ticrate angle/horizon adjustments/targets, returning sums or interpolated sums of angle/horizon values.

Main enhancements here aside from better code is.

* No longer passing 50 million game-side variables through to functions as pointers since we can just pass a struct through, or use struct methods instead.
* Re-calculated horizon pitch following much review and exposed these as a few inlines as well as method calls in the fixedhoriz class. Also standardised pitch on -90/90 as it should be.
* Apply mouse yaw input in true degrees akin to how we apply mouse pitch input as pitch. This makes the sensitivities feel largely 1:1 given the same scale.

All games have been tested, including known trouble spots. Not saying there will be absolutely zero issues but it should be a fairly safe inclusion.

Further work to be done here would be to convert fixedhoriz into BAM like binangle once the proposed pitch code here is confirmed to be correct.

### CODE REVIEW

**Comment by coelckers** [comment]
This will be merged after the 0.7.2 release,

**Comment by mjr4077au** [comment]
Awesome 😁.

**Comment by mjr4077au** [comment]
Quick note on this. I've found that I'm getting integer truncation on horz and avel when it goes through the network, which I believe is isolated to these lines in `UnpackUserCmd()`: https://github.com/coelckers/Raze/blob/79cd5e47315fdf6b9c1b8ce2d362a8db16d8ce0c/source/core/d_protocol.cpp#L162-L165

When I change `ReadLong()` to `ReadFloat()`, I get terribly erratic behaviour in-game. Could there be an issue with that function or is there another spot that I should be looking at?

**Comment by mjr4077au** [comment]
Just on this prior to merging, can I please ask for help with the savegame system for Duke? The player's angle/horizon stuff is currently commented out just to get it to work.

Short of adding a new prototype into serializer.h for binangle/lookangle/fixedhoriz, I'm not sure how best to save these new classes. Apologies that I forgot to address this in my opening PR.

**Comment by coelckers** [comment]
> Short of adding a new prototype into serializer.h for binangle/lookangle/fixedhoriz, I'm not sure how best to save these new classes. Apologies that I forgot to address this in my opening PR.

That's precisely what you should do.

**Comment by mjr4077au** [comment]
To do that though, I believe I will have to include binaryangle.h in serializer.h? As such, is it OK to move binaryangle.h from core to common to facilitate?

**Comment by coelckers** [comment]
No, neither. It's enough to do a forward declaration of FSerializer in binaryangle.h so you can do the prototype.
Look at quotemgr.h for an example.

**Comment by mjr4077au** [comment]
I'll have to look at this tonight or early next week as I need more concentration than I can give it at the moment. Just got my injured cat back from the vet and he's very high maintenance after his broken leg.

**Comment by mjr4077au** [comment]
@coelckers I hope how I've done this in 271eb1c3fa33de45bbf62ed80e4b7f64a3d87ec1 is OK. Tested and working well but please let me know if anything needs changing.

**Pull request merged**
