### PR TITLE
- Duke3D: Tie player input to framerate

### PR DESCRIPTION
**Pull request by mjr4077au**
OK, third time's the charm...

Been familiarising myself with git and with a powerful combination of git, SVN and Sublime Merge, I've been able to properly cherry-pick commits, edit accordingly and preserve proper credits for the originating code.

These commits, cherry-picked and adjusted to suit Raze really improve input response for the mouse. The game with these commits feels 1:1 with GZDoom, yquake2 etc and I think truly improves the experience.

### CODE REVIEW

**Comment by mjr4077au** [comment]
Apologies, pressed the wrong button like a goose.

**Comment by sinisterseed** [comment]
So, I took some time from my regular testing activities to check out this PR that I've noticed you have since merged into your fork here: https://github.com/mjr4077au/Raze/commits/master

I built Raze from your master ( 493010f ) and I have to say it does indeed work quite gracefully. Being rather sensitive to input lag myself, I can definitely confirm the changes make a noticeable difference, especially when coupled with VSync which currently does cause a little bit of input lag without this.

With these changes, I think the input gets as raw as it possibly can - and on par with GZDoom ;) .

**Comment by mjr4077au** [comment]
Thank you for the feedback, I'm glad to have some feedback on this 😄. Just need to test my RR one further now that Rides Again and Deer Huntin' work again as both have vehicles like boats, motorbikes etc.

Once Graf reviews and hopefully merges these, I'll probably delete my fork. Only forked to create these branches, and only merged my branch into my master from pure laziness so I could build this on Arch Linux from a pre-made PKGBUILD without mucking around 😉.

**Comment by coelckers** [comment]
Merged manually

**Pull request closed without merging**
