### PR TITLE
- enable fly cheat for shadow warrior. in other games it is currently…

### PR DESCRIPTION
**Pull request by madame-rachelle**
… ignored, but I think Redneck Rampage and Blood both need it at some point too

it makes more 3D-oriented maps like "Sumo Sky Place" a lot easier to navigate, and the cheat was present in the original game.

### CODE REVIEW

**Comment by mjr4077au** [comment]
That's awesome to see this cheat restored, and in an accessible way via the console as well 😁. It'd be good if we could get the original mechanism that was commented out going in an accessible way.

I wonder if we could add a key to the buttonMap for this and have it check for the keystroke in `PlayerFlyKey()` instead of the scancode for J? Thoughts?

**Comment by madame-rachelle** [comment]
I understand somewhat what you are saying and the structure you are referring to is something I remember seeing at some point in the past when manipulating ZDoom code.

However, it does seem to be complicating this particular issue in an unpleasant way - I understand adding yet another global bool "is a bad thing". It probably would be preferable to shove this into the player struct somehow, instead. But to me, messing with the keymappings for code that forcibly unpresses a key in order to prevent key repeats every frame seems like a less desirable way to do this. I believe that manipulating the key struct should only be done by input code, as a general goal, even if that is not the way Build games presently do things. And that was the reason for the removal and replacement of the entire function.

However, yeah, as you seem to be pointing out, adding a global variable might not be best either, hence why this got stuck in a pull request instead of directly committed.

**Comment by mjr4077au** [comment]
I wasn't really thinking about the global as such. One more global in a game that has 50 million doesn't really matter, it'd only be a problem if a concerted effort was put into eliminating those and another one came through.

What I was getting at is that it's great that this cheat is restored via the console, but it'd be great if it could be extended to use J or another bound key while god-mode is on, just like the original behaviour for those old school players who know what they're doing (or even newbies following a cheat guide on the internet).

**Comment by madame-rachelle** [comment]
Well - the code here allows you to do "bind j fly" - just it no longer has the godmode safeguard in place. But otherwise, binding that key would work identically with the old behavior.

**Comment by madame-rachelle** [comment]
On that note however, it would be possible to do a "FlyIfGod" ccmd and bind J as a default key to that.

**Comment by mjr4077au** [comment]
There's a few ways it could be tackled for sure. Maybe the voodoo keybind in the modern age isn't so great after all. If there's a bound key for this, then it probably should be exposed to the menus, but then you're exposing a cheat in the menu which isn't great either. I'm sure Graf will chime in when he wakes up.

For what it is, I don't see any problems with this, I just wanted to discuss the original behaviour so it doesn't get lost/forgotten. Regarding the global, the player struct should probably have a bitfield for enabled cheats to get rid of all the globals. Noclip is currently a flag and must have been originally, so I don't know why it has a bit and the others didn't get the same love...

**Comment by madame-rachelle** [comment]
Heh, a voodoo keybind might be a tad too confusing to an end-user. :) I agree with everything else though.

**Comment by coelckers** [comment]
Binding J to something that only activates the fly mode when god mode is on is the best option. The original code for this was just too fucked up and had to go away.

But how to deal with this? The original implementation here is broken by design, which is why I deactivated it, so without doing a lot of reworking I don't see an easy fix. It's probably best to guard the cheat against multiplayer/demos and only allow it in single player games with god mode on. Then the implementation really does not matter.

**Comment by madame-rachelle** [comment]
Okay, "fly" ccmd now does not work if you don't have god mode on. It already does the same checks as god mode does, if it needs any further then I need to know exactly what functions have to be called for such checks.

**Comment by coelckers** [comment]
The only thing it may need later is a multiplayer check because the toggle is not player-specific . For now it's ok.

**Pull request merged**
