### PR TITLE
[Blood] Add vanilla enemies cvar

### PR DESCRIPTION
**Pull request by carnivoroussociety**
This PR adds the new command `cl_bloodvanillaenemies`. By setting it to true it will restore the following vanilla bugs:

- Cerberus uselessly spinning on lava
- Tiny Caleb using the wrong type on burning state
- Burning enemies not taking damage after burnTime has reached zero
- Burning cultists extinguished in water randomly switching to shotgun/tommy gun types
- Using flawed GetClosestSpriteSectors() for enemy sight calculation/beast's stomp attack

I've also added a `cl_bloodvanillaexplosions` check when calculating the tesla's alt fire damage, as it uses sector scanning.

`cl_bloodvanillaenemies` should be exposed on the game settings, but as I don't know how to access the language spreadsheet on Google Docs I'll leave that up to someone else to add.

Additionally, I've new set the new explosions behavior flag to use EDuke's superior clipmove functionality, which resolves the issues with high speed projectiles phasing through enemies. However this will not be used for flame based projectiles as it changes the damage per second output of the hellhound/spray weapon attacks.

### CODE REVIEW

**Comment by coelckers** [comment]
If you need access to the language sheet, here's the link. https://docs.google.com/spreadsheets/d/1pvwXEgytkor9SClCiDn4j5AH7FedyXS-ocCbsuQIXDU/edit?usp=sharing

If you have a Google account you can request editing access. If you do not have a Google account, you can make all the remaining edits to the code and then post the new text here in the discussion.

**Comment by carnivoroussociety** [comment]
Thanks! The only text missing now is `$ENEMY_BEHAVIOR` which google translates suggest the following.

- CZ: Chování nepřítele
- DE: Feindliches verhalten
- ES: Comportamiento enemigo
- EO: Konduto de malamiko
- FI: Vihollisen käyttäytyminen
- FR: Comportement de l'ennemi
- IT: Comportamento del nemico
- JP: 敵の行動
- KO: 적 행동
- NL: Vijandelijk gedrag
- PL: Zachowanie wroga
- PT: Comportamento Inimigo
- RO: Comportamentul dușman
- RU: Поведение врага
- SR: Непријатељско понашање

**Comment by coelckers** [comment]
Let's better skip Google Translate here. That's a job for the actual translators. English is enough.

**Comment by carnivoroussociety** [comment]
Sure, I don't know the usual procedure for adding new interfaces but `$ENEMY_BEHAVIOR` along with the missing `$OPTVAL_OLD` will need to be added.

I don't have a google account so unfortunately someone with the raze team will have to add these two keywords.

- ENEMY_BEHAVIOR: `Enemy Behavior`
- OPTVAL_OLD: `Old` or `Original`

**Comment by sinisterseed** [comment]
I created a new "Compatibility Options" category at the end of the sheet and added both entries so far.

**Comment by carnivoroussociety** [comment]
Thank you.

This is off topic but there is a fix for missiles/TNT not registering a sprite hit. This is caused by ClipMove() failing to detect sprite hits. For NBlood I was able to fix this by changing the build engine's compatibility flag to ENGINE_EDUKE32 before calling ClipMove(), which performs some additional checks. I believe the same flags are present in Raze, but under the name `ENGINECOMPATIBILITY_NONE`. I'll be testing to ensure that the same fix works in Raze.

**Comment by carnivoroussociety** [comment]
I can confirm that this same fix works with Raze. It is now included with the explosions behavior cvar.

https://user-images.githubusercontent.com/38839485/130057933-1abc4de3-40a4-441b-b678-04ce2f0c058b.mp4


https://user-images.githubusercontent.com/38839485/130058117-632b947c-e9a7-407f-a49e-facfc543daef.mp4


https://user-images.githubusercontent.com/38839485/130057491-0cc62216-363d-4189-a76d-1a53da58f549.mp4


https://user-images.githubusercontent.com/38839485/130057595-f7280f57-6cbc-4c7a-95da-4829e50a02fc.mp4

**Comment by Gaerzi** [comment]
> Let's better skip Google Translate here. That's a job for the actual translators. English is enough.

Yep. For example the French phrase you provided would translate back as "behavior of the single solitary lone unique singular enemy". I'm exaggerating a bit on purpose but it doesn't work!

**Comment by carnivoroussociety** [comment]
Thank you!

**Comment by mjr4077au** [comment]
@carnivoroussociety thanks so much for all your fixes and works, especially around renaming some of those disassembly variables. Hope to see more from you in the future 😁.

**Pull request merged**
