### PR TITLE
Menu System: Add confirmation to FOptionMenuItemSafeCommand()

### PR DESCRIPTION
**Pull request by mjr4077au**
- Resolves 'https://forum.zdoom.org/viewtopic.php?f=340&t=67721'.

image

### CODE REVIEW

**Comment by mjr4077au** [comment]
@coelckers, this built fine locally in MSVC. Not sure what's wrong with Clang... Let me know what needs changing and will push another commit :)

**Comment by mjr4077au** [comment]
Not sure that 2nd commit is the right way to fix the Clang issue or not, but will stand by for feedback.

**Comment by coelckers** [comment]
msg.GetChars() would be the correct way.

**Comment by mjr4077au** [comment]
Force pushed to drop the improper way of doing it.

**Pull request merged**
