### PR TITLE
All Games: sine/cosine uplift and misc angle stuff

### PR DESCRIPTION
**Pull request by mjr4077au**
PR'ing this on the back of previous discussions.

* Wrap `sintable[]` access with shift-aware inline functions `bsin()` and `bcos()`. Example: `sintable[ang & 2047] >> 2` -> `bsin(ang, -2)`.
* Define `bsinf()` and `bcosf()` as double-precision Build sine/cosine functions with shift awareness and to replace `calcSinTableValue()`.
* Replace `sintable[]` access within all games with `bsin()` and `bcos()`.
* Replace `Sin()` and `Cos()` within Exhumed with `bsin()` and `bcos()`.
* Define double precision `getangle()` function as `bvectangf()`.
* Define inline conversion wrappers for `bvectangf()` to Build, Q16.16 and BAM scaling.
* Define function `getincangbam()` to avoid scaling BAM angles to Q16.16 game-side.
* Refine multiple overloads for `PlayerAngle` struct method `addadjustment()` and remove game-side format conversions to accomodate previous single method overload.
* Repeat of above for `PlayerAngle` struct method `settarget()`.

### CODE REVIEW

**Comment by mjr4077au** [comment]
Please also ignore some of the commit notes referencing `buildutils`. I was taking a different path initially and didn't go back to remove the keyword, but can do so and force push.

**Comment by coelckers** [comment]
It was too much to check every little change, but what I checked was ok. I only made a few edits to binaryangle.h

**Comment by mjr4077au** [comment]
Thanks, Graf 😄. I think the references were left over from when I was playing with templates. Probably doesn't matter if it's by reference or value when they're inline functions anway.

Regarding the use of `g_sin()`, should we also do this for the `fcos()`/`fsin()`/`ftan()` methods on binangle and lookangle classes for consistency?

**Comment by coelckers** [comment]
Yes, sure. it should be consistent.

**Pull request closed without merging**
