### PR TITLE
Resolve raze.pk3 via search paths

### PR DESCRIPTION
**Pull request by bkoropoff**
Linux installs typically don't have it next to the program binary

### CODE REVIEW

**Comment by Cacodemon345** [comment]
Does it still allow the compiled binary to be ran from the build directory without installing?

**Comment by bkoropoff** [comment]
Hmm, it's supposed to (`lookfirstinprogdir` parameter to `BaseFileSearch`), but it doesn't seem to work if you remove `.` from the search path in the config file.  Let me see what's going on...

**Comment by bkoropoff** [comment]
OK, I was hitting an unrelated bug when trying to load raze.pk3 from the build directory.  Pushed a fix for it as well.

**Comment by coelckers** [comment]
> 
> 
> Linux installs typically don't have it next to the program binary

... which begs the question why Linux is doing such dumb things to begin with - the files are intricately coupled and cannot work without each other.

**Pull request merged**
