### PR TITLE
Hacks to make IF launch again after gamefunc changes in 57cb22f13589bd3c3c6d88b6e731648b92308de1.

### PR DESCRIPTION
**Pull request by mjr4077au**
Repairs this: 
image

Also re-ordered gamefuncs to 1:1 match EDuke32.

### CODE REVIEW

**Comment by coelckers** [comment]
And here's why I see no chance to keep long term support for this game - its effects on engine design are just too invasive. :(

I think it may be better to create a fork of the engine from an earlier date, make the backend work with that and leave it as-is then.

**Comment by mjr4077au** [comment]
The problem with not supporting IF is that you wouldn't be supporting any EDuke32 mod at that point. What it's using is what's exposed for anyone to use, albeit with some code-side hacks.

I noted in the backend_unification branch that it was defaulting to the RedNukem backend for Duke 3D. This is great from a standard gameplay point of view but will leave a number of mods that need the features of EDuke 2.0/2.1 and EDuke32 unusable. Even simple mods like some of the HRPs (High Resolution Packs) do not run on RedNukem due to the incomplete CON support.

FWIW, while the frame-rate is terrible compared to master, IF does play better graphically under the backend_unification branch. Whether this is just because the GL depth buffer is off again, I'm not sure.

**Comment by coelckers** [comment]
The branch is unfinished and there's several problems with it. The main objective was to get a foundation for developing a new renderer. Unfortunately it won't play nice with Polymost.

Regarding EDuke, yes I know. Raze was mostly a learning experience for me, with what I know today I'd do some things differently. The most important thing I learned is that if you want EDuke32 support you have to fully commit to how it does things and that's not really where I want to go.
All the other games never expose the internal design this openly to modding, not even RedNukem.

**Comment by mjr4077au** [comment]
I think the direction in which things are going is great and am glad you've taken the initiative on this project. My commentary was just that, commentary.

I don't think Raze necessarily has to follow suite with EDuke32 and support it 1:1. I think a lot of people are looking at the project as a clean break to become something better and that's great :)

**Pull request merged**
