### PR TITLE
Blood: Rebalance q16mlook.

### PR DESCRIPTION
**Pull request by mjr4077au**
This one is more subjective, I guess. I think the horizonal scaling is too fast and others on the forums have agreed with me, but I don't know if it's like that to be accurate to the DOS version. Being a Nuke.YKT project, I'd assume so.

I will leave this one in your good hands for consideration.

- Make scaling more consistent with other games.
- Fix CONSTEXPR to constexpr.
- Remove usage of macro 'F16()' by using explicit fix16_from_*() type.

### CODE REVIEW

**Comment by coelckers** [comment]
Please remove the constexpr entirely. This is a clear case of someone not understanding what the keyword even does. At best these should be const, but even that is mostly irrelevant here.

**Comment by mjr4077au** [comment]
Removed the constexpr as requested. These are probably best defined a bit globally rather than continually being redefined across four files.

Regarding your comment on the other PR for Blood input, obviously anything and everything can be changed but it'd probably cause an uproar as I imagine it's how it's meant to be, apparently.

**Comment by mjr4077au** [comment]
@coelckers with the most recent commit, is that the best/right way to define a global variable?

**Comment by coelckers** [comment]
No. Please revert this. The best thing to do here is just to remove the constexpr keyword and leave them in place.

**Comment by mjr4077au** [comment]
Dropped the commit and force-pushed.

**Pull request merged**
